# Generated by Django 2.0.2 on 2018-05-28 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgge_path', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Things',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('price', models.CharField(blank=True, max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='thing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='display_section.Things'),
        ),
    ]
