# Generated by Django 2.0.2 on 2018-04-04 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business_formula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('descript', models.CharField(max_length=255)),
                ('business_id', models.IntegerField()),
                ('keywords', models.CharField(max_length=64)),
                ('params', models.CharField(max_length=128)),
                ('formula', models.CharField(max_length=128)),
                ('status', models.SmallIntegerField()),
                ('table_type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Business_operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=64)),
                ('step', models.SmallIntegerField()),
                ('business_id', models.IntegerField()),
                ('keywords', models.CharField(max_length=64)),
                ('status', models.SmallIntegerField()),
                ('table_type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Business_production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('product', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('business_id', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('keywords', models.CharField(max_length=128)),
                ('status', models.SmallIntegerField()),
                ('table_type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Business_structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=64)),
                ('parent_id', models.IntegerField()),
                ('path', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=64)),
                ('area', models.CharField(max_length=64)),
                ('status', models.SmallIntegerField()),
                ('table_type', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Emotional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16)),
                ('table_type', models.CharField(max_length=32)),
                ('emotion_type', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
                ('status', models.SmallIntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensitive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16)),
                ('table_type', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
                ('status', models.SmallIntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16)),
                ('parent_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('status', models.SmallIntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterIndexTogether(
            name='business_structure',
            index_together={('parent_id',), ('name',), ('bank',)},
        ),
        migrations.AlterIndexTogether(
            name='business_production',
            index_together={('product',), ('business_id',), ('name',)},
        ),
        migrations.AlterIndexTogether(
            name='business_operation',
            index_together={('name',), ('business_id',)},
        ),
        migrations.AlterIndexTogether(
            name='business_formula',
            index_together={('name',), ('business_id',)},
        ),
    ]
