# Generated by Django 2.0.2 on 2018-05-28 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emotional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16)),
                ('table_type', models.CharField(max_length=32)),
                ('emotion_type', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
                ('status', models.SmallIntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Sensitive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16)),
                ('table_type', models.CharField(max_length=32)),
                ('count', models.IntegerField()),
                ('status', models.SmallIntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Synonyms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=16)),
                ('parent_id', models.IntegerField()),
                ('count', models.IntegerField()),
                ('status', models.SmallIntegerField()),
                ('create_time', models.DateTimeField()),
            ],
        ),
    ]
